[package]
name = "zerotier_desktop_ui"
version = "0.1.0"
authors = ["Adam Ierymenko <adam.ierymenko@zerotier.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
web-view = { path = "web-view", features = ["edge"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
ureq = { version = "*", features = [] }
crc64fast = "*"
