[package]
name = "zerotier_desktop_ui"
version = "0.1.0"
authors = ["Adam Ierymenko <adam.ierymenko@zerotier.com>"]
edition = "2018"

[dependencies]
web-view = { path = "web-view" }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
ureq = "*"
