[package]
name = "zerotier_desktop_ui"
version = "0.1.0"
authors = ["Adam Ierymenko <adam.ierymenko@zerotier.com>"]
edition = "2018"

[dependencies]
ureq = { version = "*", features = [] }
web-view = { version = "0.7", features = ["edge"] }
serde = "*"
serde_json = "*"
