[target.x86_64-apple-darwin]
rustflags=["-C", "link-arg=-mmacosx-version-min=10.13"]

[build.aarch64-apple-darwin]
rustflags=["-C", "link-arg=-mmacosx-version-min=10.13"]

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[target.'cfg(target_os = "macos")'.dependencies]
plist = "^1"
web-view = { path = "web-view", features = [] }

[target.'cfg(windows)'.dependencies]
winreg = "^0"
